import NavBar from "./bottomNavBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-screen h-screen flex flex-col">
          <div className=" flex w-full h-full">{children}</div>
          <div className="bg-gray-800 flex w-full h-16">
            <NavBar />
          </div>
        </div>
      </body>
    </html>
  );
}
